### ISSUE TITLE
Error: No content provider

### ISSUE THREAD

**Issue by Rohan-Kumar-Jain** [ajumal-ashraf-dev/react-native-pdf-to-image#1]
Successfully linked. But got an error while converting pdf to image

  RNPdfToImage.convert(response.path)
      .then(image=>{console.log(image)})
      .catch(err=>{console.log(err)})
    });

An error msg:

  Error: No content provider: /data/user/0/com.ae/cache/D317.pdf

**Comment by ajumal-ashraf-dev** [comment]
Looks like a file access issue. Could you try moving the file to a different folder not in the cache and try passing the uri again?

**Comment by Rohan-Kumar-Jain** [comment]
I correct it. Now it is working. But I am not able to see the image which is created.

**Comment by Rohan-Kumar-Jain** [comment]
I got the path where the image gets created
